site_name: Портфолио Бельской Юлии # Название сайта
site_description: Профессиональное портфолио # Описание сайта, добавляется в meta-теги
theme: # Тема сайта, информация о ее параметрах
  name: material # Название темы
  logo: images/logo.svg # Ссылка на логотип сайта, логотип добавляется в папку `docs/images`
  font:
    text: Roboto Mono # Шрифт текста
    code: Roboto Mono # Шрифт для текста кода
  language: ru # Язык
  palette: # Настройки светлой и тёмной тем
    # Настройки светлой темы
    - scheme: default 
      toggle:
        icon: material/weather-sunny # Иконка для активации светлой темы
        name: Выключить солнышко # Всплывающий текст-подсказка
      primary: deep purple   # Основной цвет
      accent: white    # Акцентный цвет
      # вы можете использовать любой цвет из списка: 
      # red; pink; purple; deep purple; indigo; blue; light blue; cyan; teal; 
      # green; light green; lime; yellow; amber; orange; deep orange; brown; 
      # grey; blue grey; black; white

    # Настройки тёмной темы
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Позвать солнышко
      primary: deep purple  # Основной цвет
      accent: white # Акцентный цвет
      # вы можете использовать любой цвет из списка: 
      # red; pink; purple; deep purple; indigo; blue; light blue; cyan; teal; 
      # green; light green; lime; yellow; amber; orange; deep orange; brown; 
      # grey; blue grey; black; white
  features: # настройки функциональностей темы
    # - navigation.sections # Добавление разделов верхнего уровня в боковом меню, отключение спойлеров в боковом меню
    - navigation.path # Хлебные крошки
    - navigation.indexes # Позволяет создавать корневые страницы разделов меню. Корневая страница должна лежать в папке раздела и называться index.md. Пример использования корневых страниц приведен ниже в настройках nav
    - navigation.tabs # Верхнее меню
    - navigation.tabs.sticky # Фиксация верхнего меню
    - # navigation.expand # Разворачивает спойлеры в левом меню по умолчанию
    - # toc.integrate # Фиксирует оглавление страницы в левом меню
    - navigation.top  # перемещает TOC наверх/вправо
    - navigation.tabs # вкладки навигации
    - navigation.sections # секции в навигации
    - navigation.instant # Функция быстрой загрузки страниц
    - navigation.top # Добавляет кнопку «к началу» для быстрой обратной прокрутки страницы
    - search.suggest # Подсказки при вводе поискового запроса
    - search.highlight # Подсветка результатов поиска в тексте страницы
    - content.code.copy # Кнопка копирования в блоке кода

nav: # Структура сайта
- Главная страница: index.md
- Инструкции:
  - Смена аватарки в Telegram: instructions/page1.md
- Примеры документации: 
  - Сценарий «Редактирование заметки»: examples/page2.md
  - API Specification Swagger: api/swagger-api.md
- FAQ:
  - Не активна кнопка Уравнение: FAQ/page3.md
  - Нумерация таблиц и рисунков с заданного номера: FAQ/page4.md

extra_css:
  - stylesheets/extra.css

markdown_extensions: # Расширения markdown
  - admonition # Поддержка информационных панелей (сообщений типа «Внимание», «Совет», «Примечание», etc.)
  - footnotes # Поддержка встроенных сносок на страницах
  - attr_list # Использование html-атрибутов и CSS в элементах markdown
  - md_in_html # Поддержка markdown внутри html
  - def_list # Поддержка списков определений
  - pymdownx.tabbed: # Использование вкладок (табов)
      alternate_style: true
  - pymdownx.details # Использование спойлеров (катов)
  - pymdownx.highlight: # Подсветка синтаксиса в блоках кода
      anchor_linenums: true
  - pymdownx.superfences # Поддержка вложенных блоков кода

plugins:
  - search # Плагин для подключения поиска на портале
  - tags:
      tags_allowed:
      - manual
      - markdown
      - word
      - help
  - glightbox
  - swagger-ui-tag

