name: ci
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install mkdocs-glightbox # шаг для установки плагина mkdocs-glightbox
      - run: pip install mkdocs-swagger-ui-tag # шаг для установки плагина mkdocs-swagger-ui-tag
      - run: pip install mkdocs-redoc-tag # шаг для установки плагина mkdocs-redoc-tag
      - run: pip install mkdocs_puml # шаг для установки плагина mkdocs_puml    
      - run: mkdocs gh-deploy --force